ballerina-platform/module-ballerina-file

gradle.properties

Upgrade Ballerina version

---

file-native/src/main/java/org/ballerinalang/stdlib/file/nativeimpl/Utils.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/DirectoryCallback.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/DirectoryListenerConstants.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/FSListener.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/InitEndpoint.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Register.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Start.java
file-native/src/main/java/org/ballerinalang/stdlib/file/utils/FileUtils.java
file-test-utils/src/main/java/org/ballerinalang/stdlib/file/testutils/TestUtil.java

Migrate jBallerina Runtime APIs

---

.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
file-ballerina/build.gradle
file-ballerina/src/file/tests/file-test.bal

Add release workflow

---

.github/workflows/build-master.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
file-native/src/main/java/org/ballerinalang/stdlib/file/service/DirectoryListenerConstants.java
file-native/src/main/java/org/ballerinalang/stdlib/file/utils/FileConstants.java
gradle.properties

Update github workflows

---

.github/workflows/build-master.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
README.md
file-ballerina/Ballerina.toml
file-native/build.gradle
file-native/src/main/java/module-info.java
file-test-utils/build.gradle
file-test-utils/src/main/java/module-info.java

Migrate to java 11

---

file-native/src/main/java/module-info.java
file-native/src/main/java/org/ballerinalang/stdlib/file/nativeimpl/Utils.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/DirectoryCallback.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/DirectoryListenerConstants.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/FSListener.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/InitEndpoint.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Register.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Start.java
file-native/src/main/java/org/ballerinalang/stdlib/file/utils/FileConstants.java
file-native/src/main/java/org/ballerinalang/stdlib/file/utils/FileUtils.java
file-test-utils/src/main/java/module-info.java
file-test-utils/src/main/java/org/ballerinalang/stdlib/file/testutils/TestUtil.java

Refactor ballerina runtime api usages

Migrate ballerina runtime apis

---

file-native/build.gradle
file-native/src/main/java/module-info.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/compiler/DirectoryListenerCompilerPlugin.java

Update module with new diagnostic API

---

file-ballerina/src/file/file.bal
file-ballerina/src/file/filepath/file_path.bal

Improve API docs

---

file-ballerina/file_path.bal

Update log changes

---

build.gradle
file-ballerina/Ballerina.toml
file-ballerina/build.gradle
file-ballerina/file_path.bal
file-ballerina/tests/filepath_test.bal
gradle.properties

Rename system module dependency to os

---

file-ballerina/file_path.bal
file-ballerina/windows_file_path.bal
file-native/src/main/java/org/ballerinalang/stdlib/file/service/FSListener.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Register.java

Update module with new language changes

---

build.gradle
file-ballerina/Ballerina.toml
file-ballerina/build.gradle
file-ballerina/tests/directory-listener-test.bal
gradle.properties

Migrate runtime:sleep to lang.runtime:sleep

---

file-ballerina/tests/directory-listener-test.bal
file-ballerina/tests/file-test.bal
file-ballerina/tests/filepath_test.bal

Update module with testerina changes

---

file-ballerina/service_endpoint.bal

Return error in listener init

---

file-ballerina/build.gradle

Update ballerina command to bal command
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Update ballerina command to bal command

---

build.gradle
file-native/build.gradle
file-native/src/main/java/org/ballerinalang/stdlib/file/nativeimpl/Utils.java
file-native/src/main/java/org/ballerinalang/stdlib/file/service/FSListener.java
file-native/src/main/java/org/ballerinalang/stdlib/file/utils/FileConstants.java
file-native/src/main/java/org/ballerinalang/stdlib/file/utils/FileUtils.java
file-native/src/test/java/org/ballerinalang/stdlib/file/UtilsTest.java
file-test-utils/build.gradle
file-test-utils/src/main/java/org/ballerinalang/stdlib/file/testutils/TestUtil.java
gradle.properties
spotbugs-exclude.xml

Enable checkstyle & spotbugs

---

file-native/src/main/java/org/ballerinalang/stdlib/file/utils/FileUtils.java

Update module with time module changes

---

file-ballerina/file.bal
file-ballerina/file_path.bal
file-ballerina/init.bal
file-ballerina/service_endpoint.bal
file-ballerina/tests/directory-listener-test.bal
file-ballerina/tests/file-test.bal
file-ballerina/tests/filepath_test.bal

Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Change the name of the `java` langlib module to `jballerina.java`

---

file-ballerina/Ballerina.toml
file-ballerina/Dependencies.toml
file-ballerina/build.gradle

Fixes ballerina-platform/ballerina-lang#27988

Add Dependencies.toml

---

file-ballerina/build.gradle

Update build task to revert dependencies

---

build.gradle
file-ballerina/build.gradle

Fix io version name mismatch

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
README.md
file-ballerina/build.gradle

Enable publishing of code coverage

---

README.md
file-ballerina/Package.md

Update doc links

---

.github/workflows/publish-release.yml
README.md
build.gradle
file-ballerina/Package.md
file-ballerina/build.gradle
gradle.properties

$subject as well as replacing module with package in MDs.

Enable publishing to b7a central

---

gradle.properties

Update std-lib dependency versions

---

file-native/src/main/java/org/ballerinalang/stdlib/file/utils/FileConstants.java
file-native/src/main/java/org/ballerinalang/stdlib/file/utils/FileUtils.java

Resolves: https://github.com/ballerina-platform/ballerina-standard-library/issues/975

Fix attribute names in metadata record

---

build.gradle
file-ballerina/build.gradle

Re-order Build Tasks to Publish to the Ballerina Central

---

file-ballerina/tests/filepath_test.bal

Fix test failure

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
file-ballerina/build.gradle

Remove publishing testable jar and exec artifacts

---

README.md

Add Codecov Batch in README file

Add Codecov Batch in README file

---

file-ballerina/build.gradle

> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763

Add extracted bala in the zip artifact

---

file-ballerina/file.bal
file-ballerina/file_path.bal
file-ballerina/service_endpoint.bal
file-ballerina/tests/file-test.bal
file-ballerina/tests/filepath_test.bal
file-ballerina/windows_file_path.bal

Make File APIs Isolated

---

file-ballerina/build.gradle

> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032

Add -c flag to build command

---

build.gradle
file-ballerina/build.gradle

Strip stdlib dependency version

---

README.md
file-ballerina/build.gradle

$Subject
Related issue: [#1247](https://github.com/ballerina-platform/ballerina-standard-library/issues/1247)

Fix the Ballerina.toml updating before the Ballerina push

---

file-compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/ErrorCodes.java
file-compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/FileServiceValidator.java

Introduce custom error code

---

build-config/checkstyle/build.gradle
build.gradle
file-ballerina/build.gradle
gradle.properties

Standardize build script of Ballerina module

Apply Gradle Ballerina plugin for Ballerina module build script

---

file-ballerina/build.gradle

Remove overriding testCoverageParam and use the value from the gradle plugin.

Remove overriding testCoverageParam

---

file-ballerina/service_endpoint.bal
file-compiler-plugin-test/src/test/java/io/ballerina/stdlib/file/compiler/CompilerPluginTest.java

$Subject and refactor the compiler validation test cases

Make listener class isolated

---

file-ballerina/Package.md

$Subject
Related issue: ballerina-platform/ballerina-standard-library#1462

Update Package.md links into HTML format

---

README.md

Fix the broken link in the readme

---

codecov.yml

$Subject
Related issue: [1660](https://github.com/ballerina-platform/ballerina-standard-library/issues/1660)

 Add code coverage target

---

native/src/main/java/io/ballerina/stdlib/file/nativeimpl/Utils.java

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1743

Improve delete function

---

ballerina/Dependencies.toml
ballerina/file_path.bal

Remove unused variable

---

ballerina/Dependencies.toml
native/src/main/java/io/ballerina/stdlib/file/service/FSListener.java

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2383

Add check for service-object isolation

---

ballerina/build.gradle
build.gradle

$Subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/2436

Fix ballerina publish not depending on compiler plugin tests

---

ballerina/file.bal
ballerina/file_path.bal
ballerina/tests/directory-listener-test.bal
ballerina/tests/file-test.bal
ballerina/tests/filepath_test.bal
ballerina/unix_file_path.bal
ballerina/windows_file_path.bal

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2311

Refactor the code base

---

.github/pull_request_template.md
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/trivy-scan.yml

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2483

Update trivy action to scan lib directory and update PR template

---

ballerina/Ballerina.toml
ballerina/tests/directory-listener-test.bal
build-config/resources/Ballerina.toml

Update distribution version

---

docs/spec/spec.md

Update the contents and sub-heading style

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3128

Update lang and distribution versions

---

.github/workflows/update_specs.yml
ballerina/Ballerina.toml
build-config/resources/Ballerina.toml

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3154

Add workflow to update specs

---

gradle.properties

Update versions of lang  and dependencies 

---

docs/spec/spec.md

Fix typo in the spec

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3413

Update os package version

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties
native/src/main/java/io/ballerina/stdlib/file/service/FSListener.java
native/src/main/java/io/ballerina/stdlib/file/service/endpoint/Register.java

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3517

Update the package with latest runtime API changes for type reference

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update lang and dependency versions

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/file_path.bal
ballerina/tests/filepath_test.bal
build.gradle
gradle.properties

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4382

Remove regex package usages

---

ballerina/Dependencies.toml
native/src/main/java/io/ballerina/stdlib/file/service/FSListener.java
native/src/main/java/io/ballerina/stdlib/file/service/endpoint/InitEndpoint.java
native/src/main/java/io/ballerina/stdlib/file/service/endpoint/Register.java

This is to support the build for https://github.com/ballerina-platform/ballerina-standard-library/issues/4344

Fix object getType() API usage

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
README.md
ballerina/Ballerina.toml
build-config/checkstyle/build.gradle
build-config/resources/Ballerina.toml
gradle.properties
gradle/wrapper/gradle-wrapper.properties
settings.gradle
spotbugs-exclude.xml

Migrate to Java 17

---

ballerina/Dependencies.toml
compiler-plugin-test/src/test/java/io/ballerina/stdlib/file/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/test-src/package_10/Ballerina.toml
compiler-plugin-test/src/test/resources/test-src/package_10/file_service.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/FileServiceValidator.java

$Subject 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4628

Fix bug in the compiler plugin

---

.github/workflows/build-with-bal-test-graalvm.yml

Change lang tag of graalvm build

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

Update the workflows

---

native/src/main/java/io/ballerina/stdlib/file/nativeimpl/Utils.java

Related to [#43192](https://github.com/ballerina-platform/ballerina-lang/issues/43192)

Fix invalid uses of `TypeCreator.createRecordType`

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties
native/src/main/java/io/ballerina/stdlib/file/nativeimpl/Utils.java
native/src/main/java/io/ballerina/stdlib/file/service/FSListener.java
native/src/main/java/io/ballerina/stdlib/file/utils/FileUtils.java

Migrate to new Runtime APIs

---

ballerina/Dependencies.toml
ballerina/service_endpoint.bal
ballerina/tests/directory-listener-test.bal
changelog.md
examples/file-management-system/observer/file_manager.bal

> $Subject
Part of: https://github.com/ballerina-platform/ballerina-library/issues/7494
N/A

Make listener configuration as an included parameter

---

.gitignore
changelog.md
compiler-plugin-test/build.gradle
compiler-plugin-test/src/test/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/ProcessOutputGobbler.java
compiler-plugin-test/src/test/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/StaticCodeAnalyzerTest.java
compiler-plugin-test/src/test/resources/static_code_analyzer/ballerina_packages/rule1/Ballerina.toml
compiler-plugin-test/src/test/resources/static_code_analyzer/ballerina_packages/rule1/main.bal
compiler-plugin-test/src/test/resources/static_code_analyzer/ballerina_packages/rule2/Ballerina.toml
compiler-plugin-test/src/test/resources/static_code_analyzer/ballerina_packages/rule2/main.bal
compiler-plugin-test/src/test/resources/static_code_analyzer/expected_output/rule1.json
compiler-plugin-test/src/test/resources/static_code_analyzer/expected_output/rule2.json
compiler-plugin-test/src/test/resources/testng.xml
compiler-plugin/build.gradle
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/FileCompilerPlugin.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/FilePathInjectionAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/FileRule.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/FileStaticCodeAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/InsecureDirectoryAccessAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/RuleFactory.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/RuleImpl.java
compiler-plugin/src/main/resources/rules.json
gradle.properties

Reverts ballerina-platform/module-ballerina-file#566

Revert "Revert static code rule change"

---

.gitignore
ballerina/Dependencies.toml
changelog.md
compiler-plugin-test/build.gradle
compiler-plugin-test/src/test/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/ProcessOutputGobbler.java
compiler-plugin-test/src/test/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/StaticCodeAnalyzerTest.java
compiler-plugin-test/src/test/resources/static_code_analyzer/ballerina_packages/rule1/Ballerina.toml
compiler-plugin-test/src/test/resources/static_code_analyzer/ballerina_packages/rule1/main.bal
compiler-plugin-test/src/test/resources/static_code_analyzer/ballerina_packages/rule2/Ballerina.toml
compiler-plugin-test/src/test/resources/static_code_analyzer/ballerina_packages/rule2/main.bal
compiler-plugin-test/src/test/resources/static_code_analyzer/expected_output/rule1.json
compiler-plugin-test/src/test/resources/static_code_analyzer/expected_output/rule2.json
compiler-plugin-test/src/test/resources/testng.xml
compiler-plugin/build.gradle
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/FileCompilerPlugin.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/FilePathInjectionAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/FileRule.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/FileStaticCodeAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/InsecureDirectoryAccessAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/RuleFactory.java
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/RuleImpl.java
compiler-plugin/src/main/resources/rules.json
gradle.properties

Add scan tool

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
compiler-plugin-test/src/test/resources/static_code_analyzer/expected_output/rule2.json
compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/staticcodeanalyzer/FileRule.java
compiler-plugin/src/main/resources/rules.json

Refactor the rule description for path injections
